# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import keychain.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('U', 'USERNAME'), ('E', 'EMAIL'), ('C', 'CELLPHONE')], max_length=1)),
                ('account_username', models.CharField(max_length=50)),
                ('account_password', models.CharField(max_length=50)),
                ('account_email', models.CharField(max_length=50)),
                ('account_cellphone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=25, unique=True)),
                ('app_sign_in_action_uri', models.CharField(max_length=200)),
                ('app_logo_uri', models.CharField(max_length=200)),
                ('app_public_key_uri', models.CharField(max_length=200)),
                ('app_publickey', models.FileField(upload_to=keychain.models.App.app_publickey_path)),
                ('app_logo', models.ImageField(upload_to=keychain.models.App.app_logo_path)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_action', models.CharField(choices=[('I', 'SING IN'), ('U', 'SING UP')], max_length=1, null=True)),
                ('service_secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('service_time', models.DateTimeField(verbose_name='time applied')),
                ('service_status', models.CharField(choices=[('I', 'INIT'), ('S', 'SERVICE'), ('C', 'CONFIRM'), ('E', 'EXPIRE'), ('F', 'FINISH')], max_length=1)),
                ('service_qrcode', models.CharField(max_length=200)),
                ('service_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keychain.Account')),
                ('service_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keychain.App')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('U', 'USERNAME'), ('E', 'EMAIL'), ('C', 'CELLPHONE')], max_length=1)),
                ('user_name', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('user_cellphone', models.CharField(default=None, max_length=20, null=True, unique=True)),
                ('user_device', models.CharField(max_length=20, null=True, unique=True)),
                ('user_secret', models.CharField(max_length=15, null=True)),
                ('user_cookie', models.UUIDField(null=True)),
                ('user_cookie_time', models.DateTimeField(null=True, verbose_name='cookie expire time')),
                ('user_salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keychain.App'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keychain.User'),
        ),
    ]
