# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('keychain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_cellphone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'USERNAME'), (2, 'EMAIL'), (3, 'CELLPHONE'), (4, 'USERNAME')],
                                   max_length=1),
        ),
    ]
