# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0002_auto_20160320_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keychain.App'),
        ),
    ]
